### ISSUE TITLE
Drop requirement for ipython

### ISSUE THREAD

**Issue by ahuang11** [pyviz/hvplot#101]
```
Traceback (most recent call last):
  File "testrun.py", line 5, in <module>
    import hvplot.xarray
  File "/users/user/anaconda3/envs/grb_ready/lib/python3.5/site-packages/hvplot/__init__.py", line 7, in <module>
    from holoviews.ipython import display # noqa
  File "/users/user/anaconda3/envs/grb_ready/lib/python3.5/site-packages/holoviews/ipython/__init__.py", line 5, in <module>
    from IPython import version_info
```

**Comment by philippjfr** [comment]
Thanks, we should probably just remove that import altogether. IPython makes ``display`` available in the global namespace so there's no need to import it. There's also no need to import the custom holoviews display function.
