### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by zxdawn** [pyviz/hvplot#166]
I'm trying to install `hvplot` on Windows.
There's no error when installing by `conda install -c pyviz hvplot`. But I got this error when `import hvplot`:
```
>>> import hvplot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\anaconda\lib\site-packages\hvplot\__init__.py", line 14, in <module>
    from .converter import HoloViewsConverter
  File "E:\anaconda\lib\site-packages\hvplot\converter.py", line 11, in <module>
    from bokeh.models import HoverTool
  File "E:\anaconda\lib\site-packages\bokeh\models\__init__.py", line 48, in <module>
    from ..core.property.dataspec import expr, field, value # Legacy API
  File "E:\anaconda\lib\site-packages\bokeh\core\property\dataspec.py", line 40, in <module>
    from .visual import FontSize, MarkerType
  File "E:\anaconda\lib\site-packages\bokeh\core\property\visual.py", line 29, in <module>
    import PIL.Image
  File "E:\anaconda\lib\site-packages\PIL\Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: DLL load failed: The specified module could not be found.
```

<details>
 <summary>Full environment definition</summary>

### Operating system
Win10

### conda list

```
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36he6757f0_0    defaults
affine                    2.2.2                      py_0    conda-forge
alabaster                 0.7.10           py36hcd07829_0    defaults
anaconda                  custom           py36h363777c_0    defaults
anaconda-client           1.6.5            py36hd36550c_0    defaults
anaconda-navigator        1.6.9            py36hc720852_0    defaults
anaconda-project          0.8.0            py36h8b3bf89_0    defaults
appdirs                   1.4.3                      py_1    conda-forge
arm_pyart                 1.9.1                    py36_0    conda-forge
asn1crypto                0.22.0           py36h8e79faa_1    defaults
astroid                   1.5.3            py36h9d85297_0    defaults
astropy                   2.0.2            py36h06391c4_4    defaults
attrs                     18.2.0                     py_0    conda-forge
babel                     2.5.0                    pypi_0    pypi
backcall                  0.1.0                    py36_0    defaults
backports                 1.0              py36h81696a8_1    defaults
backports.shutil_get_terminal_size 1.0.0            py36h79ab834_2    defaults
beautifulsoup4            4.6.0                    py36_0    conda-forge
bitarray                  0.8.1            py36h6af124b_0    defaults
bkcharts                  0.2              py36h7e685f7_0    defaults
blas                      1.0                         mkl    defaults
blaze                     0.11.3           py36h8a29ca5_0    defaults
bleach                    2.0.0            py36h0a7e3d6_0    defaults
bokeh                     1.0.4                    py36_0    anaconda
boost                     1.61.0              py36_vc14_0  [vc14]  anaconda
boost-cpp                 1.65.1           vc14h7942e50_3  [vc14]  anaconda
boto                      2.48.0           py36h1a776d2_1    defaults
boto3                     1.9.86                     py_0    conda-forge
botocore                  1.12.86                    py_0    conda-forge
bottleneck                1.2.1            py36hd119dfa_0    defaults
bzip2                     1.0.6                    vc14_3  [vc14]  anaconda
ca-certificates           2019.1.23                     0    defaults
cachecontrol              0.12.3           py36hfe50d7b_0    defaults
cartopy                   0.17.0          py36hdc29d4d_1000    conda-forge
certifi                   2018.11.29               py36_0    defaults
cf-units                  2.0.2           py36h452e1ab_1000    conda-forge
cf_units                  2.0.1           py36h452e1ab_1002    conda-forge
cffi                      1.10.0           py36hae3d1b5_1    defaults
cftime                    1.0.0                    py36_0    conda-forge
chardet                   3.0.4            py36h420ce6e_1    defaults
clangdev                  5.0.0                 default_0  [vc14]  conda-forge
click                     6.7              py36hec8c647_0    defaults
click-plugins             1.0.4                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               0.4.0            py36h639d8dc_0    defaults
clyent                    1.2.2            py36hb10d595_1    defaults
cmaps                     1.0.0                    pypi_0    pypi
colorama                  0.3.9            py36h029ae33_0    defaults
colorcet                  1.0.1                      py_0    pyviz
comtypes                  1.1.2            py36heb9b3d1_0    defaults
conda                     4.6.4                    py36_0    defaults
conda-build               3.0.27           py36h309a530_0    defaults
conda-env                 2.6.0                h36134e3_1    anaconda
conda-verify              2.0.0            py36h065de53_0    defaults
configobj                 5.0.6                      py_0    conda-forge
console_shortcut          0.1.1                h6bb2dd7_3    defaults
contextlib2               0.5.5            py36he5d52c0_0    defaults
cryptography              2.0.3            py36h123decb_1    defaults
curl                      7.55.1                   vc14_0  [vc14]  conda-forge
cycler                    0.10.0           py36h009560c_0    defaults
cython                    0.26.1           py36h18049ac_0    defaults
cytoolz                   0.8.2            py36h547e66e_0    defaults
dask                      1.0.0                    py36_0    defaults
dask-core                 1.0.0                    py36_0    defaults
datashader                0.6.9                      py_0    pyviz
datashape                 0.5.4            py36h5770b85_0    defaults
decorator                 4.1.2            py36he63a57b_0    defaults
descartes                 1.1.0                    py36_0    defaults
distlib                   0.2.5            py36h51371be_0    defaults
distributed               1.25.1                   py36_0    defaults
docrep                    0.2.5                      py_0    conda-forge
docutils                  0.14             py36h6012d8f_0    defaults
easyprocess               0.2.3                    pypi_0    pypi
ensure                    0.6.2                    pypi_0    pypi
entrypoints               0.2.3            py36hfd66bb0_2    defaults
et_xmlfile                1.0.1            py36h3d2d736_0    defaults
expat                     2.2.5             he025d50_1002    conda-forge
fastcache                 1.0.2            py36hffdae1b_0    defaults
filelock                  2.0.12           py36hd7ddd41_0    defaults
fiona                     1.7.10           py36h5bf8d1d_0    defaults
flask                     0.12.2           py36h98b5e8f_0    defaults
flask-cors                3.0.3            py36h8a3855d_0    defaults
freetype                  2.9.1                ha9979f8_1    defaults
freexl                    1.0.5             hd288d7e_1002    conda-forge
future                    0.17.1                py36_1000    conda-forge
gdal                      2.2.2            py36hcebd033_1    defaults
geopandas                 0.4.0                    py36_1    defaults
geos                      3.6.2             he025d50_1004    conda-forge
geotiff                   1.4.2                h2080a26_1    conda-forge
geoviews                  1.6.2                      py_0    pyviz
geoviews-core             1.6.2                      py_0    pyviz
get_terminal_size         1.0.0                h38e98db_0    defaults
gevent                    1.2.2            py36h342a76c_0    defaults
glob2                     0.5              py36h11cc1bd_1    defaults
greenlet                  0.4.12           py36ha00ad21_0    defaults
h5py                      2.7.0            py36hfbe0a52_1    defaults
hdf4                      4.2.13                   vc14_0  [vc14]  conda-forge
hdf5                      1.10.1           vc14hb361328_0  [vc14]  anaconda
heapdict                  1.0.0            py36h21fa5f4_0    defaults
holoviews                 1.11.2                   pypi_0    pypi
html5lib                  0.999999999      py36ha09b1f3_0    defaults
hvplot                    0.4.0                      py_0    pyviz
icc_rt                    2017.0.4             h97af966_0    defaults
icu                       58.2             vc14hc45fdbb_0  [vc14]  anaconda
idna                      2.6              py36h148d497_1    defaults
imageio                   2.2.0            py36had6c2d2_0    defaults
imagesize                 0.7.1            py36he29f638_0    defaults
intel-openmp              2018.0.0             hcd89f80_7    defaults
ipykernel                 5.1.0            py36h39e3cac_0    defaults
ipython                   6.5.0                    py36_0    defaults
ipython_genutils          0.2.0            py36h3c5d0ee_0    defaults
ipywidgets                7.4.2                    py36_0    defaults
iris                      2.2.0                 py36_1003    conda-forge
iso8601                   0.1.12                   pypi_0    pypi
isort                     4.2.15           py36h6198cc5_0    defaults
itsdangerous              0.24             py36hb6c5a24_1    defaults
jdcal                     1.3              py36h64a5255_0    defaults
jedi                      0.13.2                   pypi_0    pypi
jinja2                    2.9.6            py36h10aa3a0_1    defaults
jmespath                  0.9.3                      py_1    conda-forge
jpeg                      9b               vc14h4d7706e_1  [vc14]  anaconda
jsonschema                2.6.0            py36h7636477_0    defaults
jupyter                   1.0.0                    py36_7    defaults
jupyter_client            5.1.0            py36h9902a9a_0    defaults
jupyter_console           5.2.0                    py36_1    defaults
jupyter_core              4.3.0            py36h511e818_0    defaults
jupyterlab                0.35.4                   py36_0    conda-forge
jupyterlab_launcher       0.4.0            py36h22c3ccf_0    defaults
jupyterlab_server         0.2.0                      py_0    conda-forge
kealib                    1.4.7                    vc14_4    conda-forge
kiwisolver                1.0.1            py36h6538335_0    defaults
krb5                      1.14.2           vc14hfaa12e2_3  [vc14]  anaconda
lazy-object-proxy         1.3.1            py36hd1c21d2_0    defaults
libboost                  1.65.1           vc14h7b94727_3  [vc14]  anaconda
libgdal                   2.2.2                h2727f2b_1    defaults
libiconv                  1.15             vc14h29686d3_5  [vc14]  anaconda
libkml                    1.3.0                hc65d273_3    defaults
libnetcdf                 4.4.1.1              h825a56a_8    defaults
libpng                    1.6.34               h79bbb47_0    defaults
libpq                     9.6.6                hfe3f2bf_0    defaults
libspatialindex           1.8.5                h6538335_2    defaults
libspatialite             4.3.0a              h383548d_18    defaults
libssh2                   1.8.0                    vc14_2  [vc14]  conda-forge
libtiff                   4.0.9                    vc14_0  [vc14]  conda-forge
libxml2                   2.9.4            vc14h8fd0f11_5  [vc14]  anaconda
libxslt                   1.1.29           vc14hf85b8d4_5  [vc14]  anaconda
llvm-meta                 5.0.0                         0    conda-forge
llvmdev                   5.0.0                 default_1  [vc14]  conda-forge
llvmlite                  0.24.0           py36h6538335_0    defaults
locket                    0.2.0            py36hfed976d_1    defaults
lockfile                  0.12.2           py36h0468280_0    defaults
lxml                      4.1.0            py36h0dcd83c_0    defaults
lzo                       2.10             vc14h0a64fa6_1  [vc14]  anaconda
m3u8                      0.3.5                    pypi_0    pypi
markupsafe                1.0              py36h0e26971_1    defaults
matplotlib                3.0.0            py36hd159220_0    defaults
mccabe                    0.6.1            py36hb41005a_1    defaults
menuinst                  1.4.14           py36hfa6e2cd_0    defaults
mistune                   0.7.4            py36h4874169_0    defaults
mkl                       2018.0.0             h36b65af_4    defaults
mkl-service               1.1.2            py36h57e144c_4    defaults
mpmath                    0.19             py36he326802_2    defaults
msgpack-python            0.4.8            py36h58b1e9d_0    defaults
multipledispatch          0.4.9            py36he44c36e_0    defaults
munch                     2.3.2                    py36_0    defaults
navigator-updater         0.1.0            py36h8a7b86b_0    defaults
nbconvert                 5.3.1            py36h8dc0fde_0    defaults
nbformat                  4.4.0            py36h3a5bc1b_0    defaults
netcdf4                   1.3.1            py36h8bd0532_2    defaults
networkx                  2.0              py36hff991e3_0    defaults
nltk                      3.2.4            py36hd0e0a39_0    defaults
nose                      1.3.7            py36h1c3779e_2    defaults
notebook                  5.3.1                    py36_0    defaults
numba                     0.39.0           py36h830ac7b_0    defaults
numexpr                   2.6.2            py36h7ca04dc_1    defaults
numpy                     1.14.2           py36h5c71026_0    defaults
numpydoc                  0.7.0            py36ha25429e_0    defaults
odo                       0.5.1            py36h7560279_0    defaults
olefile                   0.44             py36h0a7bdd2_0    defaults
openjpeg                  2.3.0                    vc14_2    conda-forge
openmp                    5.0.0                    vc14_1  [vc14]  conda-forge
openpyxl                  2.4.8            py36hf3b77f6_1    defaults
openssl                   1.0.2p               hfa6e2cd_0    defaults
owslib                    0.17.0                     py_0    conda-forge
packaging                 16.8             py36ha0986f6_1    defaults
pandas                    0.23.4           py36h830ac7b_0    defaults
pandoc                    1.19.2.1             hb2460c7_1    defaults
pandocfilters             1.4.2            py36h3ef6317_1    defaults
param                     1.8.2                    pypi_0    pypi
parso                     0.3.4                    pypi_0    pypi
partd                     0.3.8            py36hc8e763b_0    defaults
path.py                   10.3.1           py36h3dd8b46_0    defaults
pathlib2                  2.3.0            py36h7bfb78b_0    defaults
patsy                     0.4.1            py36h42cefec_0    defaults
pdfkit                    0.6.1                    pypi_0    pypi
pep8                      1.7.0            py36h0f3d67a_0    defaults
pickleshare               0.7.4            py36h9de030f_0    defaults
pillow                    5.2.0            py36h08bbbbd_0    defaults
pip                       18.0                     pypi_0    pypi
pkginfo                   1.4.1            py36hb0f9cfa_1    defaults
plotly                    3.5.0                      py_0    conda-forge
pluggy                    0.8.1                    pypi_0    pypi
ply                       3.10             py36h1211beb_0    defaults
progress                  1.3              py36hbeca8d3_0    defaults
proj4                     4.9.3                hfa6e2cd_8    conda-forge
prompt_toolkit            1.0.15           py36h60b8f86_0    defaults
psutil                    5.4.0            py36h4e662fb_0    defaults
psycopg2                  2.7.3.1          py36h308da27_0    defaults
py                        1.4.34           py36ha4aca3a_1    defaults
pycodestyle               2.3.1            py36h7cc55cd_0    defaults
pycosat                   0.6.3            py36h413d8a4_0    anaconda
pycparser                 2.18             py36hd053e01_1    defaults
pycrypto                  2.6.1            py36he68e6e2_1    defaults
pycryptodome              3.4.8                    pypi_0    pypi
pyct                      0.4.6                      py_0    pyviz
pyct-core                 0.4.6                      py_0    pyviz
pycurl                    7.43.0           py36h086bf4c_3    defaults
pyepsg                    0.4.0                      py_0    conda-forge
pyflakes                  1.6.0            py36h0b975d6_0    defaults
pygame                    1.9.3                    pypi_0    pypi
pygments                  2.2.0            py36hb010967_0    defaults
pykdtree                  1.3.1           py36h452e1ab_1002    conda-forge
pyke                      1.1.1                 py36_1000    conda-forge
pylint                    1.7.4            py36ha4e6ded_0    defaults
pyodbc                    4.0.17           py36h0006bc2_0    defaults
pyopenssl                 17.2.0           py36h15ca2fc_0    defaults
pyorbital                 1.5.0                      py_0    conda-forge
pyparsing                 2.2.0            py36h785a196_1    defaults
pypdf2                    1.26.0                   py36_1    conda-forge
pyproj                    1.9.5.1         py36haf3c679_1006    conda-forge
pyqt                      5.9.2            py36h6538335_2    defaults
pyresample                1.10.3          py36h830ac7b_1000    conda-forge
pysal                     1.14.4.post1             py36_1    defaults
pyscreenshot              0.4.2                    pypi_0    pypi
pyshp                     1.2.12                   pypi_0    pypi
pysocks                   1.6.7            py36h698d350_1    defaults
pyspectral                0.8.4                      py_0    conda-forge
pytables                  3.4.2            py36h71138e3_2    defaults
pytesseract               0.1.7                    pypi_0    pypi
pytest                    3.2.1            py36h753b05e_1    defaults
python                    3.6.3                h9e2ca53_1    defaults
python-dateutil           2.6.1            py36h509ddcb_1    defaults
python-geotiepoints       1.1.7            py36h452e1ab_0    conda-forge
python-jsonrpc-server     0.1.2                    pypi_0    pypi
python-language-server    0.23.2                   pypi_0    pypi
pytz                      2017.2           py36h05d413f_1    defaults
pyviz-comms               0.7.0                    pypi_0    pypi
pyviz_comms               0.7.0                      py_0    pyviz
pywavelets                0.5.2            py36hc649158_0    defaults
pywin32                   221              py36h9c10281_0    defaults
pyyaml                    3.12             py36h1d1928f_1    defaults
pyzmq                     16.0.2           py36h38c27d9_2    defaults
qt                        5.9.6            vc14h62aca36_0    defaults
qtawesome                 0.4.4            py36h5aa48f6_0    defaults
qtconsole                 4.4.3                    py36_0    defaults
qtpy                      1.3.1            py36hb8717c5_0    defaults
rasterio                  0.36.0           py36hb8ea33a_1    defaults
reportlab                 3.4.0                    py36_0    defaults
requests                  2.18.4           py36h4371aae_1    anaconda
retrying                  1.3.3                    pypi_0    pypi
rope                      0.10.5           py36hcaf5641_0    defaults
rtree                     0.8.3                    py36_0    defaults
ruamel_yaml               0.11.14          py36h9b16331_2    defaults
s3transfer                0.1.13                py36_1001    conda-forge
satpy                     0.11.2             pyh326bf55_0    conda-forge
scikit-image              0.13.0           py36h6dffa3f_1    defaults
scikit-learn              0.19.1           py36h53aea1b_0    defaults
scipy                     0.19.1           py36h7565378_3    defaults
seaborn                   0.8.0            py36h62cb67c_0    defaults
selenium                  3.14.1           py36hfa6e2cd_0    conda-forge
send2trash                1.5.0                    py36_0    defaults
setuptools                36.5.0           py36h65f9e6e_0    defaults
shapely                   1.6.4.post1              pypi_0    pypi
simplegeneric             0.8.1            py36heab741f_0    defaults
singledispatch            3.4.0.3          py36h17d0c80_0    defaults
sip                       4.19.8           py36h6538335_0    defaults
six                       1.11.0           py36h4db2310_1    defaults
snappy                    1.1.7            vc14h2dea872_1  [vc14]  anaconda
snowballstemmer           1.2.1            py36h763602f_0    defaults
snuggs                    1.4.1                      py_1    conda-forge
sortedcollections         0.5.3            py36hbefa0ab_0    defaults
sortedcontainers          1.5.7            py36ha90ac20_0    defaults
sphinx                    1.6.3            py36h9bb690b_0    defaults
sphinxcontrib             1.0              py36hbbac3d2_1    defaults
sphinxcontrib-websupport  1.0.1            py36hb5e5916_1    defaults
spyder                    3.2.4            py36h8845eaa_0    defaults
sqlalchemy                1.1.13           py36h5948d12_0    defaults
sqlite                    3.25.2               hfa6e2cd_0    defaults
statsmodels               0.8.0            py36h6189b4c_0    defaults
svglib                    0.8.1                    py36_0    conda-forge
svgmanip                  0.0.4                    pypi_0    pypi
svgutils                  0.2.0                    py36_0    conda-forge
sympy                     1.1.1            py36h96708e0_0    defaults
tblib                     1.3.2            py36h30f5020_0    defaults
testpath                  0.3.1            py36h2698cfe_0    defaults
tk                        8.6.7            vc14hb68737d_1  [vc14]  anaconda
tobac                     0.8                      pypi_0    pypi
toolz                     0.8.2            py36he152a52_0    defaults
tornado                   4.5.2            py36h57f6048_0    defaults
tqdm                      4.29.1                     py_0    conda-forge
trackpy                   0.4.1                      py_1    conda-forge
traitlets                 4.3.2            py36h096827d_0    defaults
trollimage                1.6.3                      py_0    conda-forge
trollsift                 0.3.2                      py_0    conda-forge
typing                    3.6.2            py36hb035bda_0    defaults
udunits2                  2.2.27.6          h252784a_1001    conda-forge
uncertainties             3.0.2                    py36_1    conda-forge
unicodecsv                0.14.1           py36h6450c06_0    defaults
urllib3                   1.22             py36h276f60a_0    defaults
vc                        14                   h2379b0c_2    defaults
vs2015_runtime            14.0.25123           hd4c4e62_2    defaults
wcwidth                   0.1.7            py36h3d5aa90_0    defaults
webencodings              0.5.1            py36h67c50ae_1    defaults
werkzeug                  0.12.2           py36h866a736_0    defaults
wheel                     0.29.0           py36h6ce6cde_1    defaults
widgetsnbextension        3.4.2                    py36_0    defaults
win_inet_pton             1.0.1            py36he67d7fd_1    defaults
win_unicode_console       0.5              py36hcdbd4b5_0    defaults
wincertstore              0.2              py36h7fe50ca_0    defaults
wrapt                     1.10.11          py36he5f5981_0    defaults
xarray                    0.11.2                   pypi_0    pypi
xerces-c                  3.2.0                h6538335_2    conda-forge
xgcm                      0.1.0                    pypi_0    pypi
xlrd                      1.1.0            py36h1cb58dc_1    defaults
xlsxwriter                1.0.2            py36hf723b7d_0    anaconda
xlwings                   0.11.7                   py36_0    anaconda
xlwt                      1.3.0            py36h1a4751e_0    defaults
xz                        5.2.4             h2fa13f4_1001    conda-forge
yaml                      0.1.7            vc14h4cb57cf_1  [vc14]  anaconda
ykdl                      1.5.4                    pypi_0    pypi
you-get                   0.4.1011                 pypi_0    pypi
youtube-dl                2017.12.23               pypi_0    pypi
zict                      0.1.3            py36h2d8e73e_0    anaconda
zlib                      1.2.11           vc14h1cdd9ab_1  [vc14]  anaconda
```

**Comment by zxdawn** [comment]
After uninstall anaconda and reinstall miniconda ... It works again ... If that happens again, I'll re-open it.

**Comment by jbednar** [comment]
Glad to hear it!  Probably just uninstalling and reinstalling `pillow` would have had the same effect.
